# Install node using the official repository
# https://deb.nodesource.com/setup_6.x -> 13.x
---

- dynamic_defaults:
    hostvars: '{{ hostvars[inventory_hostname] }}'
    defaults: '{{ node_dynamic_defaults }}'
    must_match: yes
  tags: [node, always]

- block:
    - include_tasks: setup-repository-{{ ansible_pkg_mgr }}.yml

    - name: Install node packages
      package:
        name: '{{ node_packages }}'
        state: "{{ (_node_repo is change)|ternary('latest', 'present') }}"

    - name: Check node command is available
      command:
        node --version
      changed_when: _node_command is failure
      check_mode: no
      ignore_errors: yes
      register: _node_command

    - name: Add symlink nodejs = node
      file:
        src: /usr/bin/nodejs
        dest: /usr/bin/node
        state: link
      when: _node_command is failure

    - name: Check node version
      command:
        node --version
      changed_when: no
      check_mode: no
      failed_when: _node_version is failure or _node_version.stdout[1:node_version|string|length+1] != node_version|string
      register: _node_version
  become: yes
  tags: [node, packages]
